export interface EvolutionRoundConfig {
  round: number;
  label: string;
  phaseBadge: string;
  tweakSummary: string;
  formulaNote: string;
  /** How strongly structural branches lerp toward mates (0.68 = spindly cables, 0.015 = pure botanical silhouette) */
  seekLean: number;
  /** Da Vinci pipe exponent gamma in r_0^gamma = r_1^gamma + r_2^gamma (1.35 = bloated clubs, 2.12 = true area conservation) */
  daVinciGamma: number;
  /** Child branch area fraction alpha */
  splitAlpha: number;
  /** Momentum-balanced parent deflection factor at forks (0.0 = straight rods, 0.92 = gnarled sympodial zig-zag) */
  sympodialFactor: number;
  /** Mean fork angle in degrees */
  forkAngleDeg: number;
  /** Step-size multiplier per branch depth order */
  depthStepDecay: number;
  /** Multiplier on branching probability for outer twigs (depth 2..6) */
  twigRamificationBoost: number;
  /** Maximum branch depth order allowed */
  maxDepth: number;
  /** Progressive stem taper rate along internodes */
  taperRate: number;
  /** Crown shyness repulsion strength between neighboring twig clouds */
  crownShynessStrength: number;
  /** Capillary anastomosis cross-linking strength for vascular rhizomes */
  anastomosisStrength: number;
  /** Coherent 3D sinusoidal curl/gnarl amplitude */
  curvinessAmp: number;
  /** Minimum branch depth before appendages/leaves spawn (0 = blobs on trunk, 1-2 = clean bare trunks) */
  appendageMinDepth: number;
  /** Maximum visual radius of appendages so leaves never swallow primary runners */
  maxAppThickness: number;
}

export const EVOLUTION_ROUNDS: EvolutionRoundConfig[] = [
  {
    round: 1,
    label: "Step 1 · Initial Spindly & Club Baseline",
    phaseBadge: "STEP 1 (BASELINE)",
    tweakSummary:
      "Original uncalibrated state: 68% mate-seeking lerp snaps forks into parallel spindly ribbons; 0.86x fork radius bloats rhizome area by +51% per split with 0° parent deflection.",
    formulaNote: "r₁ = 0.86 r₀, r₂ = 0.88 r₀ (Area = 1.51 r₀²) | θ_parent = 0° | seekLerp = 0.68",
    seekLean: 0.68,
    daVinciGamma: 1.32,
    splitAlpha: 0.5,
    sympodialFactor: 0.0,
    forkAngleDeg: 26,
    depthStepDecay: 0.92,
    twigRamificationBoost: 0.55,
    maxDepth: 2,
    taperRate: 0.12,
    crownShynessStrength: 0.0,
    anastomosisStrength: 0.0,
    curvinessAmp: 0.05,
    appendageMinDepth: 0,
    maxAppThickness: 1.55,
  },
  {
    round: 2,
    label: "Round 2 · Reduce Global Seek Override",
    phaseBadge: "ROUND 2",
    tweakSummary:
      "Cut structural branch seek-homing from 0.68 to 0.45 so primary forks retain initial spread for the first 10 seconds.",
    formulaNote: "seekLerp: 0.68 → 0.45 | forkAngle: 26° → 30°",
    seekLean: 0.45,
    daVinciGamma: 1.4,
    splitAlpha: 0.48,
    sympodialFactor: 0.08,
    forkAngleDeg: 30,
    depthStepDecay: 0.89,
    twigRamificationBoost: 0.68,
    maxDepth: 3,
    taperRate: 0.18,
    crownShynessStrength: 0.01,
    anastomosisStrength: 0.01,
    curvinessAmp: 0.12,
    appendageMinDepth: 0,
    maxAppThickness: 1.35,
  },
  {
    round: 3,
    label: "Round 3 · Unlock 3rd-Order Sub-Branches",
    phaseBadge: "ROUND 3",
    tweakSummary:
      "Exempt sibling branches from frame-1 crowding fratricide so depth-3 lateral shoots survive after bifurcation.",
    formulaNote: "siblingGraceTicks: 0 → 35 | maxDepth: 3",
    seekLean: 0.34,
    daVinciGamma: 1.48,
    splitAlpha: 0.47,
    sympodialFactor: 0.15,
    forkAngleDeg: 33,
    depthStepDecay: 0.86,
    twigRamificationBoost: 0.8,
    maxDepth: 3,
    taperRate: 0.24,
    crownShynessStrength: 0.02,
    anastomosisStrength: 0.02,
    curvinessAmp: 0.18,
    appendageMinDepth: 0,
    maxAppThickness: 1.2,
  },
  {
    round: 4,
    label: "Round 4 · Fix Same-Tick Taper Deactivation",
    phaseBadge: "ROUND 4",
    tweakSummary:
      "Remove instant tick-0 branch kill when agent.tapering triggers; allow 6-step progressive terminal tapering.",
    formulaNote: "taperBudget: 0 → 6 steps | taperRate: 0.24 → 0.30",
    seekLean: 0.26,
    daVinciGamma: 1.55,
    splitAlpha: 0.46,
    sympodialFactor: 0.22,
    forkAngleDeg: 35,
    depthStepDecay: 0.84,
    twigRamificationBoost: 0.92,
    maxDepth: 3,
    taperRate: 0.3,
    crownShynessStrength: 0.03,
    anastomosisStrength: 0.03,
    curvinessAmp: 0.25,
    appendageMinDepth: 0,
    maxAppThickness: 1.05,
  },
  {
    round: 5,
    label: "Round 5 · Introduce Da Vinci Pipe Scaling (γ = 1.65)",
    phaseBadge: "ROUND 5",
    tweakSummary:
      "Replace fixed 0.86x rhizome radius multiplier with power-law pipe scaling (γ = 1.65) to curb club-like thickening.",
    formulaNote: "r_child = r₀ α^(1/1.65), r_leader = r₀ (1-α)^(1/1.65)",
    seekLean: 0.2,
    daVinciGamma: 1.65,
    splitAlpha: 0.45,
    sympodialFactor: 0.28,
    forkAngleDeg: 37,
    depthStepDecay: 0.82,
    twigRamificationBoost: 1.05,
    maxDepth: 4,
    taperRate: 0.35,
    crownShynessStrength: 0.04,
    anastomosisStrength: 0.04,
    curvinessAmp: 0.32,
    appendageMinDepth: 1,
    maxAppThickness: 0.95,
  },
  {
    round: 6,
    label: "Round 6 · Strip Trunk Blobs (Clean Primary Stems)",
    phaseBadge: "ROUND 6",
    tweakSummary:
      "Suppress heavy appendage spawning on depth-0 primary trunks and arteries so woody/vascular skeletons become visible.",
    formulaNote: "appendageMinDepth: 0 → 1 | maxAppThickness: 0.88",
    seekLean: 0.17,
    daVinciGamma: 1.72,
    splitAlpha: 0.44,
    sympodialFactor: 0.34,
    forkAngleDeg: 39,
    depthStepDecay: 0.8,
    twigRamificationBoost: 1.15,
    maxDepth: 4,
    taperRate: 0.4,
    crownShynessStrength: 0.05,
    anastomosisStrength: 0.045,
    curvinessAmp: 0.4,
    appendageMinDepth: 1,
    maxAppThickness: 0.88,
  },
  {
    round: 7,
    label: "Round 7 · First Sympodial Node Torque (0.40)",
    phaseBadge: "ROUND 7",
    tweakSummary:
      "Apply opposite-sign angular deflection to parent stems at every fork, eliminating straight-line laser trunks.",
    formulaNote: "θ_parent = -0.40 · θ_child · (α / (1 - α))",
    seekLean: 0.15,
    daVinciGamma: 1.78,
    splitAlpha: 0.43,
    sympodialFactor: 0.4,
    forkAngleDeg: 41,
    depthStepDecay: 0.79,
    twigRamificationBoost: 1.24,
    maxDepth: 4,
    taperRate: 0.44,
    crownShynessStrength: 0.06,
    anastomosisStrength: 0.05,
    curvinessAmp: 0.48,
    appendageMinDepth: 1,
    maxAppThickness: 0.82,
  },
  {
    round: 8,
    label: "Round 8 · Differentiate Excurrent Whorls vs Vase Splitting",
    phaseBadge: "ROUND 8",
    tweakSummary:
      "Add radial 3-4 branch horizontal whorls for Pine and 3-way deliquescent vase crown division for Elm.",
    formulaNote: "Pine: 86° radial whorls | Elm: 3-way 32° crown division",
    seekLean: 0.13,
    daVinciGamma: 1.82,
    splitAlpha: 0.42,
    sympodialFactor: 0.45,
    forkAngleDeg: 43,
    depthStepDecay: 0.78,
    twigRamificationBoost: 1.32,
    maxDepth: 4,
    taperRate: 0.48,
    crownShynessStrength: 0.065,
    anastomosisStrength: 0.055,
    curvinessAmp: 0.55,
    appendageMinDepth: 1,
    maxAppThickness: 0.78,
  },
  {
    round: 9,
    label: "Round 9 · Introduce Elastic Gravitropic Droop for Willow",
    phaseBadge: "ROUND 9",
    tweakSummary:
      "Add thickness-dependent downward gravity bending (-Y) once outer branch radius drops below 35% of base thickness.",
    formulaNote: "ΔD_y = -g_droop · (1 - r / r₀)² for depth ≥ 2",
    seekLean: 0.11,
    daVinciGamma: 1.86,
    splitAlpha: 0.41,
    sympodialFactor: 0.5,
    forkAngleDeg: 45,
    depthStepDecay: 0.77,
    twigRamificationBoost: 1.4,
    maxDepth: 4,
    taperRate: 0.5,
    crownShynessStrength: 0.07,
    anastomosisStrength: 0.06,
    curvinessAmp: 0.62,
    appendageMinDepth: 1,
    maxAppThickness: 0.74,
  },
  {
    round: 10,
    label: "Step 10 · Midpoint Refinement (Balanced Pipe-Model & Sympodial Forks)",
    phaseBadge: "STEP 10 (MIDPOINT)",
    tweakSummary:
      "Midpoint milestone: Da Vinci pipe conservation (γ = 1.90) + 55% sympodial node torque + 4-order branching hierarchy. Clear bough-to-limb step-down, though terminal twig filigree is still medium-coarse.",
    formulaNote: "γ = 1.90 (r₁,r₂ ≈ 0.69 r₀) | θ_parent = -0.55 θ_child | maxDepth = 4 | seekLerp = 0.09",
    seekLean: 0.09,
    daVinciGamma: 1.9,
    splitAlpha: 0.4,
    sympodialFactor: 0.55,
    forkAngleDeg: 46,
    depthStepDecay: 0.76,
    twigRamificationBoost: 1.5,
    maxDepth: 4,
    taperRate: 0.54,
    crownShynessStrength: 0.08,
    anastomosisStrength: 0.065,
    curvinessAmp: 0.68,
    appendageMinDepth: 1,
    maxAppThickness: 0.7,
  },
  {
    round: 11,
    label: "Round 11 · Unlock 5th-Order Canopy Ramification",
    phaseBadge: "ROUND 11",
    tweakSummary:
      "Raise maxBranchDepth to 5 and shorten outer internode cooldowns so secondary limbs burst into tertiary twig clusters.",
    formulaNote: "maxDepth: 4 → 5 | twigRamificationBoost: 1.50 → 1.68",
    seekLean: 0.075,
    daVinciGamma: 1.94,
    splitAlpha: 0.39,
    sympodialFactor: 0.62,
    forkAngleDeg: 48,
    depthStepDecay: 0.74,
    twigRamificationBoost: 1.68,
    maxDepth: 5,
    taperRate: 0.58,
    crownShynessStrength: 0.09,
    anastomosisStrength: 0.07,
    curvinessAmp: 0.74,
    appendageMinDepth: 1,
    maxAppThickness: 0.66,
  },
  {
    round: 12,
    label: "Round 12 · True Area-Conserving Da Vinci Exponent (γ = 2.00)",
    phaseBadge: "ROUND 12",
    tweakSummary:
      "Enforce exact cross-sectional area conservation (r₀² = r₁² + r₂²) so vascular rhizomes and oak boughs step down sharply at every node.",
    formulaNote: "γ = 2.00 (r₁² + r₂² = r₀²) | splitAlpha = 0.38",
    seekLean: 0.06,
    daVinciGamma: 2.0,
    splitAlpha: 0.38,
    sympodialFactor: 0.68,
    forkAngleDeg: 50,
    depthStepDecay: 0.73,
    twigRamificationBoost: 1.8,
    maxDepth: 5,
    taperRate: 0.62,
    crownShynessStrength: 0.1,
    anastomosisStrength: 0.075,
    curvinessAmp: 0.8,
    appendageMinDepth: 1,
    maxAppThickness: 0.62,
  },
  {
    round: 13,
    label: "Round 13 · Scale-Dependent 3D Curl Tortuosity",
    phaseBadge: "ROUND 13",
    tweakSummary:
      "Scale sinusoidal curl frequency with branchDepth (0.08 + 0.055·depth) so boughs sweep in broad S-curves while twigs crinkle tightly.",
    formulaNote: "ω_curl(d) = 0.08 + 0.055·d | curvinessAmp = 0.88",
    seekLean: 0.05,
    daVinciGamma: 2.03,
    splitAlpha: 0.38,
    sympodialFactor: 0.73,
    forkAngleDeg: 52,
    depthStepDecay: 0.72,
    twigRamificationBoost: 1.9,
    maxDepth: 5,
    taperRate: 0.65,
    crownShynessStrength: 0.11,
    anastomosisStrength: 0.08,
    curvinessAmp: 0.88,
    appendageMinDepth: 1,
    maxAppThickness: 0.6,
  },
  {
    round: 14,
    label: "Round 14 · Crown Shyness Repulsion Field (Pic 3 Channels)",
    phaseBadge: "ROUND 14",
    tweakSummary:
      "Strengthen inverse-distance tip repulsion between neighboring twig clouds (r = 9 units) to sculpt clean sky channels like Pic 3.",
    formulaNote: "F_shy = 0.125 · (1 - d / R_shy) away from neighbor tips",
    seekLean: 0.04,
    daVinciGamma: 2.05,
    splitAlpha: 0.37,
    sympodialFactor: 0.77,
    forkAngleDeg: 53,
    depthStepDecay: 0.71,
    twigRamificationBoost: 2.0,
    maxDepth: 5,
    taperRate: 0.68,
    crownShynessStrength: 0.125,
    anastomosisStrength: 0.085,
    curvinessAmp: 0.94,
    appendageMinDepth: 1,
    maxAppThickness: 0.58,
  },
  {
    round: 15,
    label: "Round 15 · Capillary Anastomosis for Vascular Rhizomes",
    phaseBadge: "ROUND 15",
    tweakSummary:
      "Enable mid-range attraction (3.5–11 units) on depth ≥ 2 rhizome capillaries so creeping tendrils fuse into webbed loops.",
    formulaNote: "anastomosisStrength = 0.095 for 3.5 < d < 11.0 (depth ≥ 2)",
    seekLean: 0.035,
    daVinciGamma: 2.07,
    splitAlpha: 0.37,
    sympodialFactor: 0.81,
    forkAngleDeg: 54,
    depthStepDecay: 0.7,
    twigRamificationBoost: 2.08,
    maxDepth: 5,
    taperRate: 0.7,
    crownShynessStrength: 0.135,
    anastomosisStrength: 0.095,
    curvinessAmp: 1.0,
    appendageMinDepth: 1,
    maxAppThickness: 0.56,
  },
  {
    round: 16,
    label: "Round 16 · Asymmetric Dominant-vs-Lateral Split Ratios",
    phaseBadge: "ROUND 16",
    tweakSummary:
      "Tune splitAlpha = 0.36 so primary oak/rhizome leaders retain 80% diameter while lateral branches step down to 60%, matching natural silhouettes.",
    formulaNote: "α = 0.36 → r_leader = 0.81 r₀, r_lateral = 0.61 r₀",
    seekLean: 0.028,
    daVinciGamma: 2.08,
    splitAlpha: 0.36,
    sympodialFactor: 0.84,
    forkAngleDeg: 55,
    depthStepDecay: 0.69,
    twigRamificationBoost: 2.15,
    maxDepth: 6,
    taperRate: 0.72,
    crownShynessStrength: 0.14,
    anastomosisStrength: 0.1,
    curvinessAmp: 1.05,
    appendageMinDepth: 1,
    maxAppThickness: 0.55,
  },
  {
    round: 17,
    label: "Round 17 · 6th-Order Micro-Twig Filigree (depth = 6)",
    phaseBadge: "ROUND 17",
    tweakSummary:
      "Unlock depth-6 terminal twiglets with rapid geometric step decay (0.68^depth) for fine lacy canopy edges.",
    formulaNote: "stepSize(d) = stepBase · max(0.18, 0.68^d) | maxDepth = 6",
    seekLean: 0.024,
    daVinciGamma: 2.1,
    splitAlpha: 0.36,
    sympodialFactor: 0.87,
    forkAngleDeg: 56,
    depthStepDecay: 0.68,
    twigRamificationBoost: 2.22,
    maxDepth: 6,
    taperRate: 0.74,
    crownShynessStrength: 0.148,
    anastomosisStrength: 0.105,
    curvinessAmp: 1.1,
    appendageMinDepth: 1,
    maxAppThickness: 0.54,
  },
  {
    round: 18,
    label: "Round 18 · Conical Whorl Taper & Weeping Curtain Drape",
    phaseBadge: "ROUND 18",
    tweakSummary:
      "Refine Pine height-dependent whorl shortening (1 - 0.68·y/H) and increase Willow terminal curtain length.",
    formulaNote: "L_whorl(y) = L₀(1 - 0.68 y/H) | Willow droop = 0.16",
    seekLean: 0.02,
    daVinciGamma: 2.11,
    splitAlpha: 0.36,
    sympodialFactor: 0.89,
    forkAngleDeg: 57,
    depthStepDecay: 0.68,
    twigRamificationBoost: 2.28,
    maxDepth: 6,
    taperRate: 0.76,
    crownShynessStrength: 0.154,
    anastomosisStrength: 0.108,
    curvinessAmp: 1.14,
    appendageMinDepth: 1,
    maxAppThickness: 0.53,
  },
  {
    round: 19,
    label: "Round 19 · Terminal Foliar Clustering & Fine Needle Caps",
    phaseBadge: "ROUND 19",
    tweakSummary:
      "Concentrate foliage/buds on outer twigs (depth ≥ 2) with 0.52 max radius cap so primary & secondary boughs stay crisply articulated.",
    formulaNote: "appendageMinDepth = 2 for trunks | capMinThickness = 0.025",
    seekLean: 0.018,
    daVinciGamma: 2.12,
    splitAlpha: 0.36,
    sympodialFactor: 0.91,
    forkAngleDeg: 58,
    depthStepDecay: 0.67,
    twigRamificationBoost: 2.34,
    maxDepth: 6,
    taperRate: 0.78,
    crownShynessStrength: 0.158,
    anastomosisStrength: 0.11,
    curvinessAmp: 1.18,
    appendageMinDepth: 2,
    maxAppThickness: 0.52,
  },
  {
    round: 20,
    label: "Step 20 · Converged Natural Botanical Architecture (Pic 3 & 4)",
    phaseBadge: "STEP 20 (FINAL)",
    tweakSummary:
      "Converged natural form: strict Da Vinci pipe rule (γ = 2.12), 92% sympodial node torque, 6-order crooked twig filigree, 0.16 crown-shyness sky channels, and clean vascular/woody skeletons.",
    formulaNote: "γ = 2.12 | θ_parent = -0.92 θ_child (α/(1-α)) | maxDepth = 6 | seekLerp = 0.015",
    seekLean: 0.015,
    daVinciGamma: 2.12,
    splitAlpha: 0.36,
    sympodialFactor: 0.92,
    forkAngleDeg: 58,
    depthStepDecay: 0.67,
    twigRamificationBoost: 2.4,
    maxDepth: 6,
    taperRate: 0.8,
    crownShynessStrength: 0.16,
    anastomosisStrength: 0.115,
    curvinessAmp: 1.22,
    appendageMinDepth: 2,
    maxAppThickness: 0.5,
  },
];

export function getEvolutionStepConfig(roundOrStep?: number): EvolutionRoundConfig {
  const r = roundOrStep || 20;
  const clamped = Math.max(1, Math.min(20, Math.round(r)));
  return EVOLUTION_ROUNDS[clamped - 1];
}
